// ============================================================
// Domain Types
// ============================================================

/** User role */
export enum UserRole {
  USER = 'user',
  ADMIN = 'admin',
}

/** Processing status for media & render tasks */
export enum ProcessingStatus {
  PENDING = 'pending',
  PROCESSING = 'processing',
  COMPLETED = 'completed',
  FAILED = 'failed',
}

/** Media type */
export enum MediaType {
  VIDEO = 'video',
  IMAGE = 'image',
  AUDIO = 'audio',
}

/** Project clip style */
export enum ClipStyle {
  FAST_PACED = 'fast_paced',
  SLOW = 'slow',
  BEAT_SYNC = 'beat_sync',
}

/** Template usage mode */
export enum TemplateMode {
  STRICT = 'strict',   // 严格复刻模板节奏
  REFERENCE = 'reference', // 仅参考风格
}

/** Transition type */
export enum TransitionType {
  CUT = 'cut',
  FADE = 'fade',
  DISSOLVE = 'dissolve',
  SLIDE = 'slide',
  WIPE = 'wipe',
  ZOOM = 'zoom',
}

// ============================================================
// User
// ============================================================

export interface User {
  id: string;
  username: string;
  email: string;
  avatar?: string;
  role: UserRole;
  createdAt: string;
  updatedAt: string;
}

// ============================================================
// Media
// ============================================================

export interface Media {
  id: string;
  userId: string;
  type: MediaType;
  filename: string;
  originalName: string;
  mimeType: string;
  size: number;
  duration?: number;
  width?: number;
  height?: number;
  thumbnailPath?: string;
  filePath: string;
  tags: MediaTag[];
  analysis?: MediaAnalysis;
  status: ProcessingStatus;
  createdAt: string;
  updatedAt: string;
}

export interface MediaTag {
  id: string;
  mediaId: string;
  name: string;
  category: string; // character | technique | emotion | scene | custom
  confidence: number;
  isAutoGenerated: boolean;
}

export interface MediaAnalysis {
  id: string;
  mediaId: string;
  sceneDescription?: string;
  transcription?: string;
  keyframeDescriptions?: string[];
  colorPalette?: string[];
  motionIntensity?: number; // 0-1
  sentiment?: string;
  createdAt: string;
}

// ============================================================
// Project
// ============================================================

export interface Project {
  id: string;
  userId: string;
  name: string;
  description?: string;
  script?: string;
  clipStyle: ClipStyle;
  targetDuration?: number;
  status: ProcessingStatus;
  thumbnailPath?: string;
  scenes: Scene[];
  createdAt: string;
  updatedAt: string;
}

export interface Scene {
  id: string;
  projectId: string;
  mediaId?: string;
  order: number;
  startTime?: number;
  endTime?: number;
  caption?: string;
  transition?: TransitionType;
  transitionDuration?: number;
  duration: number;
  sourceText?: string; // 对应的解说词段落
  matchScore?: number; // AI匹配分数
}

// ============================================================
// Template
// ============================================================

export interface Template {
  id: string;
  userId?: string; // null = system built-in
  name: string;
  description?: string;
  isBuiltIn: boolean;
  thumbnailPath?: string;
  analysis?: TemplateAnalysis;
  createdAt: string;
}

export interface TemplateAnalysis {
  id: string;
  templateId: string;
  averageShotDuration: number;
  shotDurationDistribution: number[];
  transitionCounts: Record<string, number>;
  commonTransitions: string[];
  beatSyncPattern?: number[];
  pacingScore: number; // 0-10
  styleTags: string[];
}

// ============================================================
// Render Task
// ============================================================

export interface RenderTask {
  id: string;
  projectId: string;
  userId: string;
  status: ProcessingStatus;
  progress: number; // 0-100
  outputFormat: string;
  outputResolution: string;
  outputPath?: string;
  shareLink?: string;
  error?: string;
  createdAt: string;
  completedAt?: string;
}