import { Injectable, NotFoundException, Logger } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { AiService } from '../ai/ai.service';
import { FfmpegService } from '../ai/ffmpeg.service';
import { MediaType } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
@Injectable()
export class MediaService {
  private readonly logger = new Logger(MediaService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly aiService: AiService,
    private readonly ffmpegService: FfmpegService,
  ) {}

  async create(userId: string, file: Express.Multer.File, type: string) {
    const mediaType = type === 'video' ? MediaType.video
      : type === 'image' ? MediaType.image
      : MediaType.audio;

    const media = await this.prisma.media.create({
      data: {
        userId,
        type: mediaType,
        filename: file.filename,
        originalName: file.originalname,
        mimeType: file.mimetype,
        size: file.size,
        filePath: file.path,
      },
      include: { tags: true },
    });

    // Queue AI analysis in background
    this.analyzeMedia(media.id).catch((err) =>
      this.logger.error('Analysis failed for media ' + media.id, err),
    );

    return media;
  }

  async findAll(userId: string, filters?: { type?: string; tag?: string }) {
    const where: any = { userId };

    if (filters?.type) {
      where.type = filters.type as MediaType;
    }
    if (filters?.tag) {
      where.tags = { some: { name: filters.tag } };
    }

    return this.prisma.media.findMany({
      where,
      include: { tags: true, analysis: true },
      orderBy: { createdAt: 'desc' },
    });
  }

  async findOne(id: string, userId: string) {
    const media = await this.prisma.media.findFirst({
      where: { id, userId },
      include: { tags: true, analysis: true },
    });
    if (!media) throw new NotFoundException('Media not found');
    return media;
  }

  async update(id: string, userId: string, dto: any) {
    const media = await this.findOne(id, userId);
    return this.prisma.media.update({
      where: { id },
      data: dto,
      include: { tags: true, analysis: true },
    });
  }

  async remove(id: string, userId: string) {
    await this.findOne(id, userId);
    await this.prisma.media.delete({ where: { id } });
    return { deleted: true };
  }

  async addTags(mediaId: string, userId: string, tags: Array<{ name: string; category: string }>) {
    await this.findOne(mediaId, userId);

    const created = await Promise.all(
      tags.map((tag) =>
        this.prisma.mediaTag.create({
          data: {
            mediaId,
            name: tag.name,
            category: tag.category,
            isAutoGenerated: false,
          },
        }),
      ),
    );
    return created;
  }

  async analyzeMedia(mediaId: string) {
    const media = await this.prisma.media.findUnique({ where: { id: mediaId } });
    if (!media) return;
    this.logger.log('Starting AI analysis for media: ' + mediaId);
    try {
      await this.prisma.media.update({ where: { id: mediaId }, data: { status: 'processing' } });
      let sceneDescription = '';
      let transcription = '';
      const tags: Array<{ name: string; category: string }> = [];
      let motionIntensity: number | null = null;
      let sentiment: string | null = null;

      if (media.type === 'image') {
        const imageBuffer = fs.readFileSync(media.filePath);
        const base64 = imageBuffer.toString('base64');
        const analysis = await this.aiService.analyzeScene(base64);
        sceneDescription = analysis.description;
        motionIntensity = analysis.motionIntensity;
        sentiment = analysis.mood;
        for (const c of analysis.characters) tags.push({ name: c, category: 'character' });
        for (const t of analysis.techniques) tags.push({ name: t, category: 'technique' });
        for (const t of analysis.tags) tags.push({ name: t, category: 'scene' });
      }

      if (media.type === 'video') {
        this.logger.log('Starting video analysis for: ' + media.filePath);
        // path imported
        // os imported
        const keyframeDir = path.join(os.tmpdir(), 'keyframes-' + mediaId);

        const frames = await this.ffmpegService.extractKeyframes(media.filePath, keyframeDir, 5);

        if (frames.length > 0) {
          const firstFrame = frames[0];
          const imageBuffer = fs.readFileSync(firstFrame);
          const base64 = imageBuffer.toString('base64');
          const analysis = await this.aiService.analyzeScene(base64);
          sceneDescription = analysis.description;
          motionIntensity = analysis.motionIntensity;
          sentiment = analysis.mood;
          for (const c of analysis.characters) tags.push({ name: c, category: 'character' });
          for (const t of analysis.techniques) tags.push({ name: t, category: 'technique' });
          for (const t of analysis.tags) tags.push({ name: t, category: 'scene' });

          if (frames.length > 1) {
            const moreDesc = [];
            for (let fi = 1; fi < frames.length; fi++) {
              const fb = fs.readFileSync(frames[fi]);
              const b64 = fb.toString('base64');
              const a = await this.aiService.analyzeScene(b64);
              if (a.description) moreDesc.push(a.description);
              for (const c of a.characters) tags.push({ name: c, category: 'character' });
              for (const t of a.techniques) tags.push({ name: t, category: 'technique' });
              for (const t of a.tags) tags.push({ name: t, category: 'scene' });
            }
            sceneDescription = [sceneDescription, ...moreDesc].filter(Boolean).join(' | ');
          }
        }

        const audioResult = await this.aiService.transcribeAudio(media.filePath);
        transcription = audioResult.text;

        try { fs.rmSync(keyframeDir, { recursive: true, force: true }); } catch {}
      }

      await this.prisma.$transaction([
        this.prisma.mediaAnalysis.upsert({
          where: { mediaId },
          update: { sceneDescription, transcription, motionIntensity, sentiment },
          create: { mediaId, sceneDescription, transcription, keyframeDescriptions: [], colorPalette: [], motionIntensity, sentiment },
        }),
        ...tags.map((tag) =>
          this.prisma.mediaTag.create({ data: { mediaId, name: tag.name, category: tag.category, confidence: 0.8, isAutoGenerated: true } }),
        ),
        this.prisma.media.update({ where: { id: mediaId }, data: { status: 'completed' } }),
      ]);
      this.logger.log('AI analysis completed for media: ' + mediaId);
    } catch (error) {
      this.logger.error('AI analysis failed for media ' + mediaId, (error as Error).stack);
      await this.prisma.media.update({ where: { id: mediaId }, data: { status: 'failed' } });
    }
  }
}
