const { PrismaClient } = require('@prisma/client');
const path = require('path');
const fs = require('fs');

const cwd = 'C:\\Users\\sy\\Documents\\Codex\\2026-06-29\\ai-1-2-ai-3-ai\\ai-clip-studio\\apps\\server';
process.chdir(cwd);
process.env.DATABASE_URL = 'file:./dev.db';

const prisma = new PrismaClient();

async function init() {
  await prisma.$connect();
  console.log('Connected to SQLite database');
  
  // User table
  await prisma.$executeRawUnsafe(
    "CREATE TABLE IF NOT EXISTS User (" +
    "id TEXT PRIMARY KEY, username TEXT UNIQUE, email TEXT UNIQUE, " +
    "password TEXT, avatar TEXT, role TEXT DEFAULT 'user', " +
    "createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP)"
  );
  console.log('User table created');
  
  // Media table
  await prisma.$executeRawUnsafe(
    "CREATE TABLE IF NOT EXISTS Media (" +
    "id TEXT PRIMARY KEY, userId TEXT, type TEXT, filename TEXT, originalName TEXT, " +
    "mimeType TEXT, size INTEGER, duration REAL, width INTEGER, height INTEGER, " +
    "thumbnailPath TEXT, filePath TEXT, status TEXT DEFAULT 'pending', " +
    "createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP, " +
    "FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE)"
  );
  console.log('Media table created');
  
  // MediaTag table
  await prisma.$executeRawUnsafe(
    "CREATE TABLE IF NOT EXISTS MediaTag (" +
    "id TEXT PRIMARY KEY, mediaId TEXT, name TEXT, category TEXT, " +
    "confidence REAL DEFAULT 1.0, isAutoGenerated INTEGER DEFAULT 0, " +
    "FOREIGN KEY (mediaId) REFERENCES Media(id) ON DELETE CASCADE)"
  );
  
  // MediaAnalysis table
  await prisma.$executeRawUnsafe(
    "CREATE TABLE IF NOT EXISTS MediaAnalysis (" +
    "id TEXT PRIMARY KEY, mediaId TEXT UNIQUE, sceneDescription TEXT, transcription TEXT, " +
    "keyframeDescriptions TEXT, colorPalette TEXT, " +
    "motionIntensity REAL, sentiment TEXT, " +
    "createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, " +
    "FOREIGN KEY (mediaId) REFERENCES Media(id) ON DELETE CASCADE)"
  );
  
  // Project table
  await prisma.$executeRawUnsafe(
    "CREATE TABLE IF NOT EXISTS Project (" +
    "id TEXT PRIMARY KEY, userId TEXT, name TEXT, description TEXT, script TEXT, " +
    "clipStyle TEXT DEFAULT 'fast_paced', targetDuration INTEGER, templateId TEXT, " +
    "templateMode TEXT, thumbnailPath TEXT, status TEXT DEFAULT 'pending', " +
    "createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP, " +
    "FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE)"
  );
  
  // Scene table
  await prisma.$executeRawUnsafe(
    "CREATE TABLE IF NOT EXISTS Scene (" +
    "id TEXT PRIMARY KEY, projectId TEXT, mediaId TEXT, " +
    "\"order\" INTEGER, startTime REAL, endTime REAL, caption TEXT, " +
    "transition TEXT DEFAULT 'cut', transitionDuration REAL, duration REAL, " +
    "sourceText TEXT, matchScore REAL, " +
    "FOREIGN KEY (projectId) REFERENCES Project(id) ON DELETE CASCADE, " +
    "FOREIGN KEY (mediaId) REFERENCES Media(id) ON DELETE SET NULL)"
  );
  
  // Template table
  await prisma.$executeRawUnsafe(
    "CREATE TABLE IF NOT EXISTS Template (" +
    "id TEXT PRIMARY KEY, userId TEXT, name TEXT, description TEXT, " +
    "isBuiltIn INTEGER DEFAULT 0, thumbnailPath TEXT, " +
    "createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, " +
    "FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE)"
  );
  
  // TemplateAnalysis table
  await prisma.$executeRawUnsafe(
    "CREATE TABLE IF NOT EXISTS TemplateAnalysis (" +
    "id TEXT PRIMARY KEY, templateId TEXT UNIQUE, " +
    "averageShotDuration REAL, shotDurationDistribution TEXT, " +
    "transitionCounts TEXT, commonTransitions TEXT, beatSyncPattern TEXT, " +
    "pacingScore REAL, styleTags TEXT, " +
    "FOREIGN KEY (templateId) REFERENCES Template(id) ON DELETE CASCADE)"
  );
  
  // RenderTask table
  await prisma.$executeRawUnsafe(
    "CREATE TABLE IF NOT EXISTS RenderTask (" +
    "id TEXT PRIMARY KEY, projectId TEXT, userId TEXT, " +
    "status TEXT DEFAULT 'pending', progress INTEGER DEFAULT 0, " +
    "outputFormat TEXT DEFAULT 'mp4', outputResolution TEXT DEFAULT '1920x1080', " +
    "outputPath TEXT, shareLink TEXT, error TEXT, " +
    "createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, completedAt DATETIME, " +
    "FOREIGN KEY (projectId) REFERENCES Project(id) ON DELETE CASCADE, " +
    "FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE)"
  );
  
  console.log('All tables created');
  
  // Verify
  const tables = await prisma.$queryRawUnsafe("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name");
  console.log('Tables:', tables.map(t => t.name).join(', '));
  
  await prisma.$disconnect();
  console.log('Database initialization complete');
}

init().catch(err => {
  console.error('Init failed:', err.message);
  process.exit(1);
});